export const FILTERS_OPTION = {
  ROLES: [
    { value: 'frontend', label: 'Frontend' },
    { value: 'ios', label: 'iOS' },
    { value: 'Android', label: 'Android' },
    { value: 'techLead', label: 'Tech Lead' },
    { value: 'backend', label: 'Backend' },
  ],
  EMPLOYEE_COUNT: [
    { value: '1-10', label: '1-10' },
    { value: '11-20', label: '11-20' },
    { value: '21-50', label: '21-50' },
    { value: '51-100', label: '51-100' },
    { value: '201-500', label: '201-500' },
  ],
  EXPERIENCE: [
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '5', label: '5' },
    { value: '6', label: '6' },
    { value: '7', label: '7' },
    { value: '8', label: '8' },
    { value: '9', label: '9' },
    { value: '10', label: '10' },
  ],
  REMOTE: [
    { value: 'Remote', label: 'Remote' },
    { value: 'Full Time', label: 'Full Time' },
    { value: 'In-Office', label: 'In-Office' },
  ],
  MIN_BASE_PAY: [
    { value: '0L', label: '0L' },
    { value: '10L', label: '10L' },
    { value: '20L', label: '20L' },
    { value: '30L', label: '30L' },
    { value: '40L', label: '40L' },
    { value: '50L', label: '50L' },
    { value: '60L', label: '60L' },
    { value: '70L', label: '70L' },
  ],
};
